Expanded integration tests.

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -1,24 +1,26 @@
 #!/usr/bin/env bash
 
 if [[ -z $1 ]]; then
-    echo "testcase path not specified" >&2
+    echo "no testcase paths specified" >&2
     exit 1
 fi
 
-# create the database
-rm -r /tmp/tmsu 2>/dev/null
-mkdir -p /tmp/tmsu
-export TMSU_DB=/tmp/tmsu/db
-tmsu info >/dev/null 2>/dev/null
+for testcase in $@; do
+    # (re)create the database
+    rm -r /tmp/tmsu 2>/dev/null
+    mkdir -p /tmp/tmsu
+    export TMSU_DB=/tmp/tmsu/db
+    tmsu info >/dev/null 2>/dev/null
 
-# run the testcase
-./$1
-export RC=$?
+    # run the testcase
+    ./$testcase
+    export RC=$?
 
-# report result
-echo -n "$1 "
-if [[ $RC -eq 0 ]]; then
-    echo "[PASS]"
-else
-    echo "[FAIL]"
-fi
+    # report result
+    echo -n "$testcase "
+    if [[ $RC -eq 0 ]]; then
+        echo "[PASS]"
+    else
+        echo "[FAIL]"
+    fi
+done
